# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:

  build:
    desc: Build the Attendify application
    cmds:
      - go build -o attendify cmd/attendify/main.go

  run:
    desc: Run the Attendify application
    cmds:
      - go run cmd/attendify/main.go

  buld-and-run:
    desc: Build and run the Attendify application
    cmds:
      - task: build
      - task: run

  # Database migration tasks
  db:migrate:
    desc: Run all pending migrations
    cmds:
      - dbmate -d internal/db/migrations up

  db:rollback:
    desc: Rollback the last migration
    cmds:
      - dbmate -d internal/db/migrations down

  db:status:
    desc: Show migration status
    cmds:
      - dbmate -d internal/db/migrations status

  db:create:
    desc: Create the database
    cmds:
      - dbmate -d internal/db/migrations create

  db:drop:
    desc: Drop the database
    cmds:
      - dbmate -d internal/db/migrations drop

  db:new:
    desc: Create a new migration file
    cmds:
      - dbmate -d internal/db/migrations new {{.CLI_ARGS}}